/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactEntry = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PartnerEntry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'companyName' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'readTime' : IDL.Nat,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const ImpactStats = IDL.Record({
  'communitiesReached' : IDL.Nat,
  'plasticReplacedKg' : IDL.Nat,
  'studentsEducated' : IDL.Nat,
  'ecoPartners' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllContactEntries' : IDL.Func([], [IDL.Vec(ContactEntry)], ['query']),
  'getAllPartnerEntries' : IDL.Func([], [IDL.Vec(PartnerEntry)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getImpactStats' : IDL.Func([], [ImpactStats], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitPartnerForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactEntry = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PartnerEntry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'companyName' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'readTime' : IDL.Nat,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const ImpactStats = IDL.Record({
    'communitiesReached' : IDL.Nat,
    'plasticReplacedKg' : IDL.Nat,
    'studentsEducated' : IDL.Nat,
    'ecoPartners' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllContactEntries' : IDL.Func([], [IDL.Vec(ContactEntry)], ['query']),
    'getAllPartnerEntries' : IDL.Func([], [IDL.Vec(PartnerEntry)], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getImpactStats' : IDL.Func([], [ImpactStats], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitPartnerForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };